# -*- coding: utf-8 -*-
"""1_5_folium_v01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1efaOUifL2EJHxl8X3cU5i9ruAFMJTWQa

### Folium 알아보기
"""

# 위도(latitude), 경도(longitude) 를 이용한 위치표시
import folium

loc = folium.Map(location=[37.546817, 126.911411])
loc

# 위치 표시, 확대 (zoom_start 값이 크면 확대큼.)
# default = 10, zoom_start

import folium

m = folium.Map(
    location=[37.5466423,126.9092281],
    zoom_start=15
)

m

m.save('map.html')

!ls

"""### 지도의 위치 찍기(Marker)"""

## 원모양의 마커
## 양화진, 성산 중학교 마커
## folium.Marker, folium.CircleMaker
## 구글 지도 이용하여 위도, 경도 확인하기
loc = folium.Map(location=[37.546817, 126.911411], zoom_start=17)

folium.Marker([37.546817, 126.911411]).add_to(loc) # 양화진 선교사 묘원
folium.Marker([37.547394, 126.915816]).add_to(loc) # 성산중학교
loc

m = folium.Map(
    location=[37.5466423,126.9092281],
    zoom_start=15
)

folium.Marker(
    location=[37.5466423,126.9092281],
    popup = 'yanghwajin',                         # 선택 시 popup
    icon = folium.Icon(color='red', icon='star')  # 아이콘 
).add_to(m)

m

"""### CircleMarker 이용"""

m = folium.Map(
    location=[37.5466423,126.9092281],
    zoom_start=15
)

folium.CircleMarker(
    location=[37.5466423,126.9092281],
    radius = 100,
    color = '#ffffgg',
    fill_color='#fffggg',
    popup = 'yanghwajin',                         # 선택 시 popup
    icon = folium.Icon(color='red', icon='star')  # 아이콘 
).add_to(m)

m

from folium import plugins

"""### Marker를 군집화 시키기 - MarkerCluster
 * Adds a MarkerCluster layer on the map.
"""

import numpy as np
import os

N = 100

data = np.array(
    [
     np.random.uniform(low=35, high=60, size=N),
     np.random.uniform(low=-12, high=30, size=N),
    ]
).T

popups = [str(i) for i in range(N)]  # Popups texts are simple numbers.

m = folium.Map([45, 3], zoom_start=4) 
plugins.MarkerCluster(data, popups=popups).add_to(m) 
m.save(os.path.join('.', 'Plugins_1.html')) 

m

"""### GeoJson 행정 구역 데이터"""

!ls

import folium

m = folium.Map(
    location=[37.5838699,127.0565831],
    zoom_start=10
)

import json
with open('seoul_muncipalities_geo.json',mode='rt',encoding='utf-8') as f:
    geo = json.loads(f.read())
    f.close()
  
folium.GeoJson(
    geo,
    name='seoul_municipalities'
).add_to(m)

m.save('map.html')
m

stamen = folium.Map(location=[45.5236, -122.6750],
                    tiles='Stamen Toner', 
                    zoom_start=13)
stamen

stamen = folium.Map(location=[45.5236, -122.6750],
                    tiles='Stamen Terrain', 
                    zoom_start=13)
stamen

"""### REF
 * https://github.com/python-visualization/folium/tree/master/examples/data
 * https://dailyheumsi.tistory.com/85
"""